export const configOfFrameWorkAPIs = {
    createDraftFrameWork :'v1/draftFrameworks/create',
    updateDraftFrameWork : "v1/draftFrameworks/update/",
    draftFrameWorkList: "v1/draftFrameworks/list",
    deleteDraftFrameWork: "v1/draftFrameworks/delete/",
    draftCriteriaCreate: "v1/draftCriteria/create",
    updateDraftCriteria:"v1/draftCriteria/update/",
    listDraftCriteria:"v1/draftCriteria/list/",
    draftCriteriaDelete:"v1/draftCriteria/delete/",
    getDraftFrameWorkDetails:"v1/draftFrameworks/details/",
    getEntityTypeList:"v1/entityTypes/canBeObserved/",
    draftEcmCreate:"v1/draftECM/create",
    draftSectionCreate:"v1/draftSections/create",
    listDraftSection:"v1/draftSections/list/",
    listDraftEcm:"v1/draftECM/list/",
    draftCreateQuestion:"v1/draftQuestions/create",
    updateDraftQuestion:"v1/draftQuestions/update/",
    draftQuestionList:"v1/draftQuestions/list/",
    deleteDraftQuestion:"v1/draftQuestions/delete/",
    detailsDraftQuestion:"v1/draftQuestions/details/",
    publishDraftFrameWork:"v1/draftFrameworks/publish/",
    draftEcmUpdate:"v1/draftECM/update/",
    draftSectionUpdate:"v1/draftSections/update/"
}